apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-backend
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-backend
  template:
    metadata:
      labels:
        app: tienda-backend
    spec:
      containers:
        - name: backend
          image: __ECR_REGISTRY__/tienda-perritos-backend:__IMAGE_TAG__
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: tienda-backend-config
            - secretRef:
                name: tienda-backend-secret

          # Se agrega Resource para que Metrics Server calcule el % de CPU y Memoria para escalar 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # HEALTH CHECKS (PROBES)
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10